version: '3'

services:
  ## services- HTTP, FTP, SSH, SMTP
  service_http_apple:
    build: /Services/HTTP
    ports:
      - 8080:80
    environment:
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - COMPANY_ID=3
      - SERVICE_ID=1
    depends_on:
      - backend

  service_ftp_intel:
    build: /Services/FTP
    ports:
      - 2121:21
    environment:
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - COMPANY_ID=2
      - SERVICE_ID=2
    depends_on:
      - backend
  service_ftp_apple:
    build: /Services/FTP
    ports:
      - 2122:21
    environment:
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - COMPANY_ID=3
      - SERVICE_ID=2
    depends_on:
      - backend

  service_smtp_intel:
    build: /Services/SMTP
    ports:
      - 2525:25
    environment:
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - COMPANY_ID=2
      - SERVICE_ID=4
    depends_on:
      - backend

  service_ssh_intel:
    build: /Services/SSH
    ports:
      - 2222:22
    environment:
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - COMPANY_ID=2
      - SERVICE_ID=3
    depends_on:
      - backend

  ## API
  backend:
    build: /backend
    ports:
      - 5000:80
    volumes:
      - ./backend/code:/app
    environment:
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      db:
        condition: service_healthy

  # Client
  frontend:
    build: /frontend
    ports:
      - 5001:3000
    environment:
      - BROWSER=none
      - docker=True
    depends_on:
      - backend

  ## Database
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: "${USERNAME_DB}"
      MYSQL_PASSWORD: "${PASSWORD_DB}"
      MYSQL_ROOT_PASSWORD: "${PASSWORD_DB}"
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./db/db_data:/var/lib/mysql:rw
      - ./db/init:/docker-entrypoint-initdb.d/:rw
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "--password=${PASSWORD_DB}",
          "ping",
          "-h",
          "localhost"
        ]
      timeout: 20s
      retries: 2
