version: '3'

services:
  ## services- HTTP, FTP, RDP, SMTP
  service_http:
    build: /Services/HTTP
    ports:
      - 8080:80
    volumes:
      - ./Services/HTTP:/app
    environment:
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
    depends_on:
      db:
        condition: service_healthy
  service_ftp:
    build: /Services/FTP
    ports:
      - 2121:21
    volumes:
      - ./Services/FTP:/app
    environment:
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
    depends_on:
      db:
        condition: service_healthy
  service_smtp:
    build: /Services/SMTP
    ports:
      - 2525:25
    volumes:
      - ./Services/SMTP:/app
    environment:
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
    depends_on:
      db:
        condition: service_healthy

  ## Logger

  ## API

  ## Client

  ## Database
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: "${USERNAME_DB}"
      MYSQL_PASSWORD: "${PASSWORD_DB}"
      MYSQL_ROOT_PASSWORD: "${PASSWORD_DB}"
    ports:
      - 3309:3306
    expose:
      - 3306
    volumes:
      - ./db/db_data:/var/lib/mysql:rw
      - ./db/init:/docker-entrypoint-initdb.d/:rw
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "--password=${PASSWORD_DB}",
          "ping",
          "-h",
          "localhost"
        ]
      timeout: 20s
      retries: 2
